# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='course',
            index_together=set([]),
        ),
        migrations.RemoveField(
            model_name='course',
            name='coursecategory',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Coursecategory',
        ),
    ]
