# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-18 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20180818_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=50, verbose_name=b'\xe5\xa7\x93\xe5\x90\x8d'),
        ),
    ]
